MemeShop/Controllers/Admin/AdminUIController.cs
using AutoMapper;
using BLL.DataTransferObjects;
using BLL.Interfaces;
using MemeShop.Models;
using MemeShop.Models.DiscountCode;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/// <summary>
/// All UI of admin pannel here
/// All logic incapsulated in AdminUIHelper class
/// </summary>
namespace MemeShop.Controllers.Admin
{
    //Admin UI Controller
    public class AdminUIController : Controller
    {
        IShopItemService itemService { get; set; }
        IDiscountCodeService discountService { get; set; }
        public AdminUIController(IShopItemService itemService, IDiscountCodeService discountService)
        {
            this.itemService = itemService;
            this.discountService = discountService;
        }
        
        //Shop items UI
        public ActionResult AdminPanel()
        {
            if (!HttpContext.Request.Cookies.AllKeys.Contains("authOk"))
                return RedirectToAction("Validation", "AdminPage");

            AdminUIHelper helper = new AdminUIHelper(itemService);
            var map = helper.MapDTOWithViewModel();

            return View(map);
        }

        //Delete/Edit current item page
        public ActionResult DeleteItem(int? id)
        {
             AdminUIHelper helper = new AdminUIHelper(itemService);
            
            return View(helper.GetCurrentUser(id));
        }

        [HttpPost]
        public ActionResult DeleteItem(int id)
        {
            AdminUIHelper helper = new AdminUIHelper(itemService);

            var model = itemService.Get(id);
            string shortPath = model.PhotoPath;
            string serverPath = Request.MapPath(helper.GetFullserverPath(id));
            helper.DeleteImageOnServer(serverPath, shortPath);
            helper.DeleteItemFromServer(id);

            return RedirectToAction("AdminPanel");
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Price,PhotoPath")]ShopItemViewModel context, HttpPostedFileBase image)
        {
            AdminUIHelper helper = new AdminUIHelper(itemService);

            string modelPath = context.PhotoPath;
            if (image != null)
            {
                string serverImgPath = Path.Combine(Server.MapPath("~/Images"), helper.GetFullImageName(image));
                image.SaveAs(serverImgPath);
                
                string deletePath = Request.MapPath(helper.GetFullserverPath(context.Id));
                helper.DeleteImageOnServer(deletePath);

                modelPath = "~/Images/" + helper.GetFullImageName(image);
            }

            helper.EditItemOnServer(context, modelPath);
            
            return RedirectToAction("AdminPanel");
        }

        //Create new item page
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ShopItemViewModel context, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                AdminUIHelper helper = new AdminUIHelper(itemService);
                
                string serverImgPath = Path.Combine(Server.MapPath("~/Images"), helper.GetFullImageName(image));
                image.SaveAs(serverImgPath);

                string modelPath = "~/Images/" + helper.GetFullImageName(image);
                
                helper.CreateItemOnServer(context, modelPath);

                return RedirectToAction("AdminPanel");
            }

            return View();
        }

        //Discount codes UI
        public ActionResult Codes()
        {
            DiscountCodesHelper helper = new DiscountCodesHelper(discountService);

            return View(helper.MapDiscountVMWithDTO());
        }

        //I made create form and all codes on one page so I use Multiple class with enum of all codes and current code model
        [HttpPost]
        public ActionResult CreateNewCode(DiscountMultupleViewModel context)
        {
            if (ModelState.IsValid)
            {
                DTODiscountCode model = new DTODiscountCode { Code = context.DiscountCodeVM.Code, DiscountPerCent = context.DiscountCodeVM.DiscountPerCent };
                discountService.Create(model);
            }
            
            return RedirectToAction("Codes");
        }
        
        public ActionResult DeleteDiscountCode(int id)
        {
            discountService.Delete(id);

            return RedirectToAction("Codes");
        }

        //IDisposable pattern to close connection to Database
        protected override void Dispose(bool disposing)
        {
            itemService.Dispose();
            base.Dispose(disposing);
        }
    }
}

MemeShop/Views/AdminUI/AdminPanel.cshtml
@model IEnumerable<MemeShop.Models.ShopItemViewModel>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin/AdminUIStyles.css" rel="stylesheet" />
    @Styles.Render("~/bundels/bootstrap")
    <title>AdminPanel</title>
</head>
<body>
    <div class="top">
        <h3 class="logo">Admin Page</h3>
        @Html.ActionLink("Discount Codes", "Codes", null, new { @class = "logoLink" })
    </div>

    <div class="createLinkWrap">
        <button id="btnLink">@Html.ActionLink("Create new Item", "Create", null, new { id = "createLink" })</button>
    </div>

    <table class="table">
        <tr>
            <th scope="col">Image</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
            <th></th>
        </tr>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td><img src="@Url.Content(item.PhotoPath)" alt="image" id="imag"/></td>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.Price</td>
                <td>@Html.ActionLink("Options", "DeleteItem", new { id = item.Id })</td>
            </tr>
            }
        </tbody>
    </table>


    @Scripts.Render("~/bundels/jsbootstrap")
</body>
</html>

MemeShop/Views/AdminUI/Codes.cshtml
@model MemeShop.Models.DiscountCode.DiscountMultupleViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin/Discount/DiscountCodesPreview.css" rel="stylesheet" />
    @Styles.Render("~/bundels/bootstrap")
    <title>Codes</title>
</head>
<body>
    <div class="top">
        <h3 id="logo">Discount Codes</h3>
        @Html.ActionLink("Admin Pannel", "AdminPanel", null, new { @class = "logoLink" })
    </div>
    <div class="createLinkWrap">
        <button id="btnLink" class="btn btn-light">Hide Form</button>
    </div>
    <div class="container" id="showOnBtnClick">
        <div class="wrap">
            @using (Html.BeginForm("CreateNewCode", "AdminUI", FormMethod.Post))
            {
                <p>Enter Discount Code here:</p>
                <p>@Html.EditorFor(m => m.DiscountCodeVM.Code)</p>
                <p>Enter how much will be the sale(in %):</p>
                <p>@Html.EditorFor(m => m.DiscountCodeVM.DiscountPerCent)</p>
                <input type="submit" value="Create" class="btn btn-success"/>
            }
        </div>
    </div>

    <table class="table">
        <tr>
            <th scope="col">Code</th>
            <th scope="col">Per Cent</th>
            <th></th>
        </tr>
        <tbody>
            @foreach (var item in Model.CodesEnum)
            {
                <tr>
                    <td>@item.Code</td>
                    <td>@item.DiscountPerCent</td>
                    <td>@Html.ActionLink("Delete", "DeleteDiscountCode", new { id = item.Id })</td>
                </tr>
            }
        </tbody>
    </table>


    @Scripts.Render("~/bundels/jsbootstrap")
    <script src="~/Scripts/DiscountCodeScripts.js"></script>    
    
</body>
</html>

MemeShop/Views/AdminUI/Create.cshtml
@model MemeShop.Models.ShopItemViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin/CreateProductStyle.css" rel="stylesheet" />
    @Styles.Render("~/bundels/bootstrap")
    <title>Create</title>
</head>
<body>
    <div class="top">
        <h3 id="logo">Create Product</h3>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="wrap">
                    @using (Html.BeginForm("Create", "AdminUI", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <h3>Enter Product name</h3>
                        <p>@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "textInp" } })</p>
                        <h3>Description</h3>
                        <p>@Html.TextAreaFor(model => model.Description, new { @class = "area" })</p>
                        <h3>Price</h3>
                        <p>@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "textInp" } })</p>
                        <h3>Picture</h3>
                        <p>@Html.TextBox("image", "", new { type = "file" })</p>

                        <input type="submit" value="Create" class="btn btn-success"/>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="backBtn">
            @Html.ActionLink("Back", "AdminPanel")
        </div>
    </div>
</body>
</html>

MemeShop/Views/AdminUI/DeleteItem.cshtml
@model MemeShop.Models.ShopItemViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin/CreateDeleteStyles.css" rel="stylesheet" />
    @Styles.Render("~/bundels/bootstrap")
    <title>DeleteItem</title>
</head>
<body>
    <div class="top">
        <h3 id="logo">Edit</h3>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="wrap">
                    <h3 id="prodName">@Model.Name</h3><hr />
                    <p id="prodDesc">@Model.Description</p>
                    <h5 id="prodPrice">@Model.Price&#36;</h5>
                    <img src="@Url.Content(Model.PhotoPath)" alt="Product Image" class="img"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="formWrap">
                    @using (Html.BeginForm("Edit", "AdminUI", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <h3>Product Name</h3>
                        <p>@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Name } })</p>

                        <h5>Description</h5>
                        <p>@Html.TextAreaFor(model => model.Description, new { @class = "form-control area", placeholder = Model.Description })</p>

                        <h5>Price</h5>
                        <p>@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Price } })</p>

                        <h5>Picture</h5>
                        @Html.TextBox("image", "", new { type = "file", @class = "form-control-file" })
                        <br />

                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.PhotoPath)
                        <input type="submit" value="Edit" class="btn btn-dark"/>
                    }
                    <hr />
                    <p>Or You can <span id="del">Delete</span> this item(be careful!)</p>
                    @using (Html.BeginForm())
                    {
                        @Html.HiddenFor(model => model.Id)
                        <input type="submit" value="Delete" class="btn btn-danger"/>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="backBtn">
            @Html.ActionLink("Back", "AdminPanel")
        </div>
    </div>

    @Scripts.Render("~/bundels/jsbootstrap")
</body>
</html>